---
- name: Install needed helper package(s)
  become: true
  package:
    name: unzip
    state: present

- name: Check for previously installed nomad
  shell: "nomad version | awk '{print $2}' | awk -F'-' '{print $1}' | sed 's/v//'"
  changed_when: False
  failed_when: False
  register: prior_nomad_version

- name: Output previously installed nomad
  debug:
    var: prior_nomad_version.stdout

- name: Create Nomad group
  become: true
  group:
    name: "{{ nomad_group }}"
    system: yes
    state: present

- name: Create Nomad user
  become: true
  user:
    name: "{{ nomad_user }}"
    shell: /bin/false
    createhome: no
    group: "{{ nomad_group }}"
    system: yes
    state: present

- name: Create Nomad data directory
  command: "mkdir -p {{ nomad_data_dir }}"

- name: Chown data directory
  command: "chown {{ nomad_user }}:{{ nomad_group }} {{ nomad_data_dir }}"

- name: Chmod data directory
  command: "chmod 0775 {{ nomad_data_dir }}"

- name: Download x86_64 Nomad
  get_url:
    url: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_amd64.zip"
    dest: "/tmp/nomad_{{ nomad_version }}_linux_amd64.zip"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: 0444
    checksum: "sha256:{{ nomad_sha256sum }}"
  when: prior_nomad_version.stdout != nomad_version

- name: Install Nomad from the zip
  unarchive:
    src: "/tmp/nomad_{{ nomad_version }}_linux_amd64.zip"
    dest: "{{ nomad_install_dir }}"
    mode: 0775
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    keep_newer: true
  when: prior_nomad_version.stdout != nomad_version

- name: Add sysconfig file
  become: true
  template:
    src: etc/sysconfig/nomad.j2
    dest: /etc/sysconfig/nomad
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: 0664

- name: Add systemd service unit
  become: true
  template:
    src: usr/lib/systemd/system/nomad.service.j2
    dest: /usr/lib/systemd/system/nomad.service
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: 0664

- meta: flush_handlers
