---
- name: daemon-reload
  become: true
  shell: systemctl daemon-reload

- name: Enable nomad
  become: true
  service:
    name: nomad
    enabled: yes

- name: Restart nomad
  become: true
  service:
    name: nomad
    state: restarted
